In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model, datasets
from sklearn.model_selection import train_test_split

In [3]:
dataset = datasets.load_iris()
dataset

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [4]:
x = dataset.data
y = dataset.target
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.4)

In [6]:
print("X Train",x_train)
print("Y_train",y_train)
print("X_Test",x_test)
print("Y_Test",y_test)

X Train [[ 5.4  3.   4.5  1.5]
 [ 5.8  2.7  3.9  1.2]
 [ 6.6  3.   4.4  1.4]
 [ 6.3  3.4  5.6  2.4]
 [ 4.3  3.   1.1  0.1]
 [ 5.7  2.8  4.1  1.3]
 [ 6.1  3.   4.9  1.8]
 [ 5.8  2.7  4.1  1. ]
 [ 5.   3.2  1.2  0.2]
 [ 7.2  3.2  6.   1.8]
 [ 6.3  2.3  4.4  1.3]
 [ 5.1  3.7  1.5  0.4]
 [ 5.8  4.   1.2  0.2]
 [ 5.6  2.9  3.6  1.3]
 [ 6.7  3.1  4.7  1.5]
 [ 6.4  3.1  5.5  1.8]
 [ 5.4  3.7  1.5  0.2]
 [ 5.6  2.8  4.9  2. ]
 [ 6.6  2.9  4.6  1.3]
 [ 6.1  2.8  4.7  1.2]
 [ 6.2  2.8  4.8  1.8]
 [ 6.   2.2  5.   1.5]
 [ 5.5  2.4  3.8  1.1]
 [ 4.4  2.9  1.4  0.2]
 [ 4.4  3.2  1.3  0.2]
 [ 6.5  3.   5.5  1.8]
 [ 5.5  3.5  1.3  0.2]
 [ 7.4  2.8  6.1  1.9]
 [ 4.6  3.1  1.5  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 7.2  3.6  6.1  2.5]
 [ 5.1  3.8  1.5  0.3]
 [ 7.7  3.8  6.7  2.2]
 [ 5.1  3.4  1.5  0.2]
 [ 6.3  3.3  6.   2.5]
 [ 5.2  2.7  3.9  1.4]
 [ 6.3  2.9  5.6  1.8]
 [ 5.9  3.   5.1  1.8]
 [ 6.7  3.1  5.6  2.4]
 [ 6.9  3.1  4.9  1.5]
 [ 6.5  2.8  4.6  1.5]
 [ 7.1  3.   5.9  2.1]
 [ 4.8  3.   1.4  0.1]
 [ 

In [7]:
regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
regr.score(x_train, y_train)

0.93482560587334529

In [9]:
regr.score(x_test, y_test)

0.92043068069037504

In [12]:
regr.predict(x_train)

array([  1.44172993e+00,   1.06092754e+00,   1.17882843e+00,
         2.13942695e+00,  -8.50956941e-02,   1.18301915e+00,
         1.62808078e+00,   9.73114366e-01,  -1.04895292e-01,
         1.70725244e+00,   1.17954274e+00,   6.33573872e-02,
        -2.47824675e-01,   1.08254804e+00,   1.29419690e+00,
         1.71515155e+00,  -1.12702537e-01,   1.83987305e+00,
         1.16059246e+00,   1.19266234e+00,   1.59789839e+00,
         1.49293336e+00,   1.02595544e+00,   3.69499784e-02,
         4.60216570e-03,   1.70396258e+00,  -1.65216943e-01,
         1.78012230e+00,   2.35496478e-02,  -3.89805554e-02,
         2.17990027e+00,  -6.21981338e-03,   2.03586149e+00,
        -5.91040182e-02,   2.29833221e+00,   1.28057018e+00,
         1.75868834e+00,   1.70179996e+00,   2.09133245e+00,
         1.30980579e+00,   1.31093583e+00,   1.90484100e+00,
        -9.07375171e-02,   1.49346849e-01,   1.10232774e-01,
        -4.45764445e-02,   1.56481098e+00,   1.03042128e+00,
         1.81889747e+00,